### ISSUE TITLE
ゲームを起動したことがあるのに「ディレクトリは存在しません」と表示される

### ISSUE THREAD

**Issue by gcrtnst** [Gakuto1112/Stormworks-JapaneseTranslation-Downloader#1]
README.md に

> 上記のディレクトリが存在しない場合は、ゲームをまだ一度も起動していない事が考えられます。一度ゲームを起動して下さい。

とありますが、私が試した限りだと languages ディレクトリはゲームを起動しただけでは自動生成されませんでした（ゲーム内で翻訳データを新規作成することで初めて生成されるようです）。手動で languages ディレクトリを作成したら、正常に動作しました。

**Comment by Gakuto1112** [comment]
報告ありがとうございます。該当フォルダが存在しない場合は生成するように変更しようかと思います。

**Comment by Gakuto1112** [comment]
[プレリリース2](https://github.com/Gakuto1112/Stormworks-JapaneseTranslation-Downloader/releases/tag/v1.0.0-pre2)に本Issueの内容を反映させました。

**Comment by gcrtnst** [comment]
動作確認しました、ありがとうございます！
